services:
  stats-server:
    build: stat/service
    container_name: stat-container
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat-db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

  stat-db:
    image: postgres:16.1
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat-db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: main
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

  main-db:
    image: postgres:16.1
    container_name: ewn-db-container
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver